import { Injectable, signal } from '@angular/core';

type Dict = Record<string, string>;

const LANG_KEY = 'java_quiz_lang';

const en: Dict = {
  'nav.levels': 'Levels',
  'home.title': 'Master Java <span class="highlight">Programming</span>',
  'home.subtitle': '50 levels of interactive Java quizzes. Progress from beginner syntax to advanced design patterns. Unlock your potential one level at a time!',
  'home.levels': '50 Levels',
  'home.questions': '500 Questions',
  'home.pass': '70% to Pass',
  'home.start': 'Start Learning',
  'home.install': 'Télécharger Application',
  'home.pdf_quiz': '📄 Quiz from PDF',
  'pdf_quiz.upload_title': 'Upload a PDF to Generate a Quiz',
  'pdf_quiz.upload_subtitle': 'Upload any PDF document and the app will automatically create a 10-question quiz based on its content.',
  'pdf_quiz.select_pdf': 'Select PDF',
  'pdf_quiz.loading': 'Loading...',
  'pdf_quiz.processing': 'Analyzing PDF and generating your quiz...',
  'pdf_quiz.pdf_quiz': '📄 PDF Quiz',
  'pdf_quiz.confirm_submit': 'You haven\'t answered all questions. Submit anyway?',
  'pdf_quiz.result_subtitle': 'Your PDF Quiz Result',
  'pdf_quiz.new_quiz': '📄 New PDF Quiz',
  'pdf_quiz.error_no_text': 'Could not extract text from this PDF. It may be a scanned document or image-based.',
  'pdf_quiz.error_generic': 'An error occurred while processing the PDF. Please try again.',
  'dashboard.title': 'Choose Your Level',
  'dashboard.subtitle': 'Complete each level with 70%+ to unlock the next',
  'dashboard.current': 'Current Level',
  'dashboard.total': 'Total Levels',
  'dashboard.passed': '✅ Passed',
  'dashboard.failed': '❌ Failed',
  'dashboard.new': '🆕 New',
  'dashboard.locked': '🔒 Locked',
  'dashboard.best': 'Best',
  'dashboard.start': 'Start',
  'dashboard.level_label': 'Level',
  'dashboard.review': 'Review',
  'dashboard.locked_btn': 'Locked',
  'quiz.questions': '10 Questions',
  'quiz.question_of': 'Question',
  'quiz.of': 'of',
  'quiz.prev': '← Previous',
  'quiz.next': 'Next →',
  'quiz.submit': 'Submit Answers',
  'quiz.not_found': 'Level not found.',
  'result.congrats': 'Congratulations!',
  'result.not_quite': 'Not Quite!',
  'result.mastered': "You've mastered Level",
  'result.need_pass': 'You need 70% to pass Level',
  'result.next_level': 'Next Level →',
  'result.all_done': "🏆 You've completed all 50 levels! You're a Java Master!",
  'result.dont_give_up': "💪 Don't give up! Review the AI feedback below and try again.",
  'result.try_again': 'Try Again 🔄',
  'result.back': 'Back to Levels',
  'result.unlocked': '✅ Level {0} is now unlocked!',
  'result.ai_title': 'Intelligent AI Feedback',
  'result.ai_subtitle': "I've analyzed your mistakes to help you improve.",
  'result.your_answer': 'Your Answer',
  'result.correct_answer': 'Correct Answer',
  'result.ai_explanation': 'AI Explanation',
  'result.no_answer': 'No answer provided',
  'result.unknown': 'Unknown',
  'footer.text': '© 2026 JavaQuiz - Master Java Programming',
  'install.already': "L'application est déjà installée sur votre appareil.",
  'install.ios': "Pour installer l'application :\n1. Appuyez sur le bouton Partager\n2. Faites défiler et appuyez sur \"Ajouter à l'écran d'accueil\"",
  'install.other': 'Pour installer l\'application, ouvrez le menu du navigateur et choisissez "Ajouter à l\'écran d\'accueil" ou "Installer".',
  'install.not_available': "Cette fonctionnalité n'est pas disponible sur votre navigateur. Veuillez utiliser Chrome ou Safari.",
  'chatbot.title': 'Assistant',
  'chatbot.placeholder': 'Ask me anything...',
};

const fr: Dict = {
  'nav.levels': 'Niveaux',
  'home.title': 'Maîtrisez Java <span class="highlight">Programming</span>',
  'home.subtitle': '50 niveaux de quiz Java interactifs. Progressez de la syntaxe débutante aux motifs de conception avancés. Libérez votre potentiel, un niveau à la fois !',
  'home.levels': '50 Niveaux',
  'home.questions': '500 Questions',
  'home.pass': '70% pour Réussir',
  'home.start': 'Commencer l\'Apprentissage',
  'home.install': 'Télécharger l\'Application',
  'home.pdf_quiz': '📄 Quiz depuis PDF',
  'pdf_quiz.upload_title': 'Téléchargez un PDF pour générer un quiz',
  'pdf_quiz.upload_subtitle': 'Téléchargez n\'importe quel document PDF et l\'application créera automatiquement un quiz de 10 questions basé sur son contenu.',
  'pdf_quiz.select_pdf': 'Choisir un PDF',
  'pdf_quiz.loading': 'Chargement...',
  'pdf_quiz.processing': 'Analyse du PDF et génération du quiz...',
  'pdf_quiz.pdf_quiz': '📄 Quiz PDF',
  'pdf_quiz.confirm_submit': 'Vous n\'avez pas répondu à toutes les questions. Soumettre quand même ?',
  'pdf_quiz.result_subtitle': 'Résultat de votre Quiz PDF',
  'pdf_quiz.new_quiz': '📄 Nouveau Quiz PDF',
  'pdf_quiz.error_no_text': 'Impossible d\'extraire le texte de ce PDF. Il s\'agit peut-être d\'un document scanné ou basé sur des images.',
  'pdf_quiz.error_generic': 'Une erreur s\'est produite lors du traitement du PDF. Veuillez réessayer.',
  'dashboard.title': 'Choisissez Votre Niveau',
  'dashboard.subtitle': 'Complétez chaque niveau avec 70%+ pour débloquer le suivant',
  'dashboard.current': 'Niveau Actuel',
  'dashboard.total': 'Nombre de Niveaux',
  'dashboard.passed': '✅ Réussi',
  'dashboard.failed': '❌ Échoué',
  'dashboard.new': '🆕 Nouveau',
  'dashboard.locked': '🔒 Verrouillé',
  'dashboard.best': 'Meilleur',
  'dashboard.start': 'Commencer',
  'dashboard.level_label': 'Niveau',
  'dashboard.review': 'Réviser',
  'dashboard.locked_btn': 'Verrouillé',
  'quiz.questions': '10 Questions',
  'quiz.question_of': 'Question',
  'quiz.of': 'sur',
  'quiz.prev': '← Précédent',
  'quiz.next': 'Suivant →',
  'quiz.submit': 'Soumettre les Réponses',
  'quiz.not_found': 'Niveau introuvable.',
  'result.congrats': 'Félicitations !',
  'result.not_quite': 'Pas Tout à Fait !',
  'result.mastered': 'Vous avez maîtrisé le niveau',
  'result.need_pass': 'Vous avez besoin de 70% pour passer le niveau',
  'result.next_level': 'Niveau Suivant →',
  'result.all_done': "🏆 Vous avez complété les 50 niveaux ! Vous êtes un Maître Java !",
  'result.dont_give_up': "💪 N'abandonnez pas ! Consultez les retours AI ci-dessous et réessayez.",
  'result.try_again': 'Réessayer 🔄',
  'result.back': 'Retour aux Niveaux',
  'result.unlocked': '✅ Le niveau {0} est maintenant débloqué !',
  'result.ai_title': 'Analyse Intelligent AI',
  'result.ai_subtitle': "J'ai analysé vos erreurs pour vous aider à progresser.",
  'result.your_answer': 'Votre Réponse',
  'result.correct_answer': 'Bonne Réponse',
  'result.ai_explanation': 'Explication AI',
  'result.no_answer': 'Aucune réponse fournie',
  'result.unknown': 'Inconnu',
  'footer.text': '© 2026 JavaQuiz - Maîtrisez la Programmation Java',
  'install.already': "L'application est déjà installée sur votre appareil.",
  'install.ios': "Pour installer l'application :\n1. Appuyez sur le bouton Partager\n2. Faites défiler et appuyez sur \"Ajouter à l'écran d'accueil\"",
  'install.other': 'Pour installer l\'application, ouvrez le menu du navigateur et choisissez "Ajouter à l\'écran d\'accueil" ou "Installer".',
  'install.not_available': "Cette fonctionnalité n'est pas disponible sur votre navigateur. Veuillez utiliser Chrome ou Safari.",
  'chatbot.title': 'Assistant',
  'chatbot.placeholder': 'Posez votre question...',
};

const ar: Dict = {
  'nav.levels': 'المستويات',
  'home.title': 'أتقن <span class="highlight">برمجة جافا</span>',
  'home.subtitle': '٥٠ مستوى من اختبارات جافا التفاعلية. تقدم من بناء الجملة للمبتدئين إلى أنماط التصميم المتقدمة. أطلق العنان لإمكانياتك مستوى واحد في كل مرة!',
  'home.levels': '٥٠ مستوى',
  'home.questions': '٥٠٠ سؤال',
  'home.pass': '٧٠٪ للنجاح',
  'home.start': 'ابدأ التعلم',
  'home.install': 'تحميل التطبيق',
  'home.pdf_quiz': '📄 اختبار من PDF',
  'pdf_quiz.upload_title': 'حمّل PDF لإنشاء اختبار',
  'pdf_quiz.upload_subtitle': 'حمّل أي مستند PDF وسيقوم التطبيق تلقائياً بإنشاء اختبار من 10 أسئلة بناءً على محتواه.',
  'pdf_quiz.select_pdf': 'اختيار PDF',
  'pdf_quiz.loading': 'جارٍ التحميل...',
  'pdf_quiz.processing': 'جارٍ تحليل PDF وإنشاء الاختبار...',
  'pdf_quiz.pdf_quiz': '📄 اختبار PDF',
  'pdf_quiz.confirm_submit': 'لم تجب على جميع الأسئلة. هل تريد الإرسال على أي حال؟',
  'pdf_quiz.result_subtitle': 'نتيجة اختبار PDF الخاص بك',
  'pdf_quiz.new_quiz': '📄 اختبار PDF جديد',
  'pdf_quiz.error_no_text': 'تعذر استخراج النص من ملف PDF هذا. قد يكون مستنداً ممسوحاً ضوئياً أو قائماً على الصور.',
  'pdf_quiz.error_generic': 'حدث خطأ أثناء معالجة PDF. يرجى المحاولة مرة أخرى.',
  'dashboard.title': 'اختر مستواك',
  'dashboard.subtitle': 'أكمل كل مستوى بنسبة ٧٠٪+ لفتح التالي',
  'dashboard.current': 'المستوى الحالي',
  'dashboard.total': 'إجمالي المستويات',
  'dashboard.passed': '✅ ناجح',
  'dashboard.failed': '❌ راسب',
  'dashboard.new': '🆕 جديد',
  'dashboard.locked': '🔒 مقفل',
  'dashboard.best': 'الأفضل',
  'dashboard.start': 'ابدأ',
  'dashboard.level_label': 'المستوى',
  'dashboard.review': 'مراجعة',
  'dashboard.locked_btn': 'مقفل',
  'quiz.questions': '١٠ أسئلة',
  'quiz.question_of': 'سؤال',
  'quiz.of': 'من',
  'quiz.prev': '→ السابق',
  'quiz.next': 'التالي ←',
  'quiz.submit': 'إرسال الإجابات',
  'quiz.not_found': 'المستوى غير موجود.',
  'result.congrats': 'تهانينا!',
  'result.not_quite': 'ليس تمامًا!',
  'result.mastered': 'لقد أتقنت المستوى',
  'result.need_pass': 'تحتاج ٧٠٪ لاجتياز المستوى',
  'result.next_level': 'المستوى التالي ←',
  'result.all_done': '🏆 لقد أكملت جميع المستويات الخمسين! أنت محترف جافا!',
  'result.dont_give_up': '💪 لا تستسلم! راجع الملاحظات أدناه وحاول مرة أخرى.',
  'result.try_again': 'حاول مرة أخرى 🔄',
  'result.back': 'العودة إلى المستويات',
  'result.unlocked': '✅ تم فتح المستوى {0}!',
  'result.ai_title': 'تحليل الذكاء الاصطناعي',
  'result.ai_subtitle': 'لقد حللت أخطائك لمساعدتك على التحسن.',
  'result.your_answer': 'إجابتك',
  'result.correct_answer': 'الإجابة الصحيحة',
  'result.ai_explanation': 'شرح AI',
  'result.no_answer': 'لم يتم تقديم إجابة',
  'result.unknown': 'غير معروف',
  'footer.text': '© ٢٠٢٦ JavaQuiz - أتقن برمجة جافا',
  'install.already': 'التطبيق مثبت بالفعل على جهازك.',
  'install.ios': 'لتثبيت التطبيق:\n١. انقر على زر المشاركة\n٢. انتقل لأسفل وانقر على "إضافة إلى الشاشة الرئيسية"',
  'install.other': 'لتثبيت التطبيق، افتح قائمة المتصفح واختر "إضافة إلى الشاشة الرئيسية" أو "تثبيت".',
  'install.not_available': 'هذه الميزة غير متاحة في متصفحك. يرجى استخدام Chrome أو Safari.',
  'chatbot.title': 'المساعد',
  'chatbot.placeholder': 'اطرح سؤالك...',
};

const all: Record<string, Dict> = { en, fr, ar };

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private lang = signal<string>(localStorage.getItem(LANG_KEY) || 'en');
  readonly currentLang = this.lang.asReadonly();

  setLanguage(lang: string) {
    this.lang.set(lang);
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }

  t(key: string): string {
    return all[this.lang()]?.[key] ?? all['en']?.[key] ?? key;
  }

  tp(key: string, ...params: string[]): string {
    let text = this.t(key);
    params.forEach((p, i) => text = text.replace(`{${i}}`, p));
    return text;
  }
}
